Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Function for ideal_gas_law
def ideal_gas_law(number_of_moles, temperature, volume):

    return 

# Tests correct equation
np.testing.assert_almost_equal(ideal_gas_law(100, 100, 0.82057338), 101325.03467270655)
print('Test 1 for Problem 1 Passed!')

# Tests correct equation
np.testing.assert_almost_equal(ideal_gas_law(1, 500, 5), 831.4462618)
print('Test 2 for Problem 1 Passed!')

# Tests for unphysical temperatures
np.testing.assert_raises(ValueError, ideal_gas_law, 1, -1, 10)
print('Test 3 for Problem 1 Passed!')

# Tests for unphysical number of moles
np.testing.assert_raises(ValueError, ideal_gas_law, -1, 1, 10)
print('Test 4 for Problem 1 Passed!')

# Tests for unphysical pressure
np.testing.assert_raises(ValueError, ideal_gas_law, 1, 1, -101325)
print('Test 5 for Problem 1 Passed!')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1730/1179617738.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0;31m# Tests correct equation[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0mnp[0m[0;34m.[0m[0mtesting[0m[0;34m.[0m[0massert_almost_equal[0m[0;34m([0m[0mideal_gas_law[0m[0;34m([0m[0;36m100[0m[0;34m,[0m [0;36m100[0m[0;34m,[0m [0;36m0.82057338[0m[0;34m)[0m[0;34m,[0m [0;36m101325.03467270655[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0mprint[0m[0;34m([0m[0;34m'Test 1 for Problem 1 Passed!'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/testing/_private/utils.py[0m in [0;36massert_almost_equal[0;34m(actual, desired, decimal, err_msg, verbose)[0m
[1;32m    596[0m     [0;32mexcept[0m [0;34m([0m[0mNotImplementedError[0m[0;34m,[0m [0mTypeError[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    597[0m         [0;32mpass[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 598[0;31m     [0;32mif[0m [0mabs[0m[0;34m([0m[0mdesired[0m [0;34m-[0m [0mactual[0m[0;34m)[0m [0;34m>=[0m [0;36m1.5[0m [0;34m*[0m [0;36m10.0[0m[0;34m**[0m[0;34m([0m[0;34m-[0m[0mdecimal[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    599[0m         [0;32mraise[0m [0mAssertionError[0m[0;34m([0m[0m_build_err_msg[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    600[0m [0;34m[0m[0m

[0;31mTypeError[0m: unsupported operand type(s) for -: 'float' and 'NoneType'
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

